# - name: Copy deployments link script to remote host
#   copy: src=linkDeployments.sh dest=/home/{{CFG_USER}}/bin owner={{CFG_USER}} group={{CFG_GROUP}} mode=0600

# Link wildfly autoloader deployments directory to the vagrant shared build directory
- name: Run deployments script
  script: linkDeployments.sh
  when: vm

# Setup wars
- name: Copy wars to remote host
  copy: src={{ARTIFACT_DIR}}/{{item.name}} dest=/home/{{CFG_USER}}/archive/{{item.name}} owner={{CFG_USER}} group={{CFG_GROUP}} mode=0600
  with_items: APPLICATION_WARS
  when: not vm

- name: Deploy wars
  shell: "/home/{{CFG_USER}}/wildfly/current/bin/jboss-cli.sh --controller={{'localhost' if wildfly_bind_addr == '0.0.0.0' else wildfly_bind_addr}} --connect --command='deploy /home/{{CFG_USER}}/archive/{{item.name}} --force'"
  with_items: APPLICATION_WARS
  environment: "{{wildfly_env}}"
  when: not vm
