---
# Stage common (all hosts) application artifacts to the control host
# For example, binary files from artifactory that are normally excluded from git repos
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create artifacts directory
      file: path={{ARTIFACT_DIR}} mode=0755 state=directory
    - name: Stage artifacts on the control host
      run_once: true
      get_url: url={{JDK_URL}}/{{JDK_ARCHIVE}} dest={{ARTIFACT_DIR}}/{{JDK_ARCHIVE}} mode=0666 validate_certs=no force=yes

# Perform application configuration of the application servers
- hosts: app-servers
  sudo: yes
  sudo_user: "{{CFG_USER}}"
  connection: ssh
  gather_facts: no
  roles:
    - app-jdk
