---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Create artifacts directory
      file: path={{ARTIFACT_DIR}} mode=0755 state=directory
    - name: Stage artifacts on the control host
      run_once: true
      get_url: url={{item.url}} dest={{ARTIFACT_DIR}}/{{item.name}} mode=0666 validate_certs=no force=no
      with_items:
        - { url: "{{JDK_URL}}/{{JDK_ARCHIVE}}", name: "{{JDK_ARCHIVE}}" }
        - { url: "{{ELASTICSEARCH_BASE_URL}}/{{ELASTICSEARCH_VERSION}}/{{ELASTICSEARCH_ARCHIVE}}", name: "{{ELASTICSEARCH_ARCHIVE}}" }
        - { url: "{{ELASTICSEARCH_DATASET_URL}}", name: "{{ELASTICSEARCH_DATASET}}" }
        - { url: "{{WILDFLY_URL}}/{{WILDFLY_ARCHIVE}}", name: "{{WILDFLY_ARCHIVE}}" }
    - name: Stage war artifacts on the control host
      run_once: true
      get_url: url={{item.url}} dest={{ARTIFACT_DIR}}/{{item.name}} mode=0666 validate_certs=no force=yes
      with_items: APPLICATION_WARS
